#principal
title: Danna Bustamante #titulo en la pestaña del navegador
email:
  - dbustamanter@unal.edu.co
  - pizza@DePeperoni.com
description: "Portafolio de Danna Bustamante" #
numberPosts: 10 #Siempre un numero aqui

#uwu
url: "https://questashaciendoaqui-vago.github.io/"
#Colecciones
collections:
  - galeria
  - fotos
